# Generated by Django 4.0.5 on 2022-07-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_opportunitiesrevenue_opportunities_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitiesrevenue',
            name='date_closed',
        ),
        migrations.AddField(
            model_name='opportunitiesrevenue',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
